basic_app/urls.py
from unicodedata import name
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^register', views.register, name="register"),
    url(r'^user_login', views.user_login, name='user_login'),
]

models_forms/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views
urlpatterns = [
    url(r'^$', views.index, name='index'),   
    url(r'basic_app/', include('basic_app.urls')),        
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'special/', views.special, name='special')
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)

    #additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm
# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
#################################
def index(request):
    return render(request,"index.html",{"page":"Home"})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are Logged in, Cooooolllll!!!!!!!!!!!! ")

def register(request):

    registered =  False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
        
    return render(request,"registration.html", {'page':"Register",'user_form':user_form,
                                                'profile_form':profile_form,
                                                'registered':registered})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Login Failed")
            print("username: {} and password: {}".format(username,password))
            invalid_details = "Invalid details .... :("
            return render(request,"login.html",{"invalid_details": invalid_details})
        
    else: 
        return render(request,"login.html",{'page':'Login'})

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{page}}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        {# Django Home Link / Admin Link / Register Link#}
        <a class="navbar-brand" href="{% url 'index' %}">SAMI-JEE 🙏</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:register' %}">Register</a>

        {# Some logic on what to display for last item#}
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% comment %} <a class="nav-link" href="#">Logout</a> {% endcomment %}
        {% else %}
          <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
          {% comment %} <a class="nav-link" href="#">Login</a> {% endcomment %}
        {% endif %}
      </div>
    </nav>

    <div class="container">
    {% block content %}
    {% endblock %}
    </div>


  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="jumbotron">
      <h1>AHAM BRAHAMHASMI 🤟</h1>
      {% if user.is_authenticated %}
          <h2>Welcome {{ user.username|upper }} 😊 </h2>
      {% else %}
          <h2>Welcome to the site!</h2>
      {% endif %}
    </div>
  </div>
  

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'basic_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>
        {{invalid_details}}

    </div>
  </div>
{% endblock %}

templates/registration.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}